import { useEffect, useState } from 'react'; import { Alert, StyleSheet, Text, View } from 'react-native';
import { apiRequest } from '../api/api-client'; import { AppButton } from '../components/ui/AppButton'; import { Screen } from '../components/ui/Screen'; import { SectionHeader } from '../components/ui/SectionHeader'; import { StateView } from '../components/ui/StateView'; import { colors } from '../theme/colors'; import { AdminMetrics } from '../types/api';
interface QueueItem { id: string; type?: string; category?: string; reason?: string; description?: string; }
interface AdminQueue { documents: QueueItem[]; reports: QueueItem[]; disputes: QueueItem[]; }
export function AdminScreen() { const [metrics, setMetrics] = useState<AdminMetrics | null>(null); const [queue, setQueue] = useState<AdminQueue | null>(null); const [error, setError] = useState(''); useEffect(() => { load(); }, []); async function load() { try { const [metricResponse, queueResponse] = await Promise.all([apiRequest<AdminMetrics>('/admin/metrics'), apiRequest<AdminQueue>('/admin/moderation')]); setMetrics(metricResponse); setQueue(queueResponse); } catch (currentError) { setError(currentError instanceof Error ? currentError.message : 'Painel indisponível.'); } }
  async function review(path: string, status: string) { try { await apiRequest(path, { method: 'PATCH', body: JSON.stringify({ status, notes: 'Analisado pelo aplicativo Home Easy.' }) }); await load(); } catch (currentError) { Alert.alert('Ação não concluída', currentError instanceof Error ? currentError.message : 'Tente novamente.'); } }
  if (error) return <Screen><StateView message={error} /></Screen>; return <Screen><SectionHeader eyebrow="Administração" title="Moderação e métricas" description="Analise documentos, denúncias e disputas pendentes." />{metrics && <View style={styles.metrics}><Metric label="Solicitações" value={metrics.totalRequests} /><Metric label="Abertas" value={metrics.openRequests} /><Metric label="Conversão" value={`${metrics.conversionRate}%`} /><Metric label="Verificações" value={metrics.pendingVerifications} /></View>}{!queue && <StateView loading message="Carregando fila..." />}{queue?.documents.map(item => <View key={item.id} style={styles.card}><Text style={styles.title}>Documento: {item.type}</Text><View style={styles.actions}><View style={styles.grow}><AppButton label="Aprovar" onPress={() => review(`/admin/verification/documents/${item.id}`, 'approved')} /></View><View style={styles.grow}><AppButton label="Rejeitar" variant="secondary" onPress={() => review(`/admin/verification/documents/${item.id}`, 'rejected')} /></View></View></View>)}{queue?.reports.map(item => <ModerationCard key={item.id} title={`Denúncia: ${item.category}`} description={item.description} onResolve={() => review(`/admin/reports/${item.id}`, 'resolved')} />)}{queue?.disputes.map(item => <ModerationCard key={item.id} title={`Disputa: ${item.reason}`} description={item.description} onResolve={() => review(`/admin/disputes/${item.id}`, 'resolved')} />)}</Screen>; }
function Metric({ label, value }: { label: string; value: string | number }) { return <View style={styles.metric}><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>; }
function ModerationCard({ title, description, onResolve }: { title: string; description?: string; onResolve(): void }) { return <View style={styles.card}><Text style={styles.title}>{title}</Text><Text style={styles.description}>{description}</Text><AppButton label="Marcar como resolvido" onPress={onResolve} /></View>; }
const styles = StyleSheet.create({ metrics: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, metric: { width: '48%', alignItems: 'center', padding: 15, borderRadius: 16, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, metricValue: { color: colors.primary, fontSize: 22, fontWeight: '900' }, metricLabel: { color: colors.textMuted, fontSize: 12 }, card: { gap: 10, padding: 16, borderRadius: 18, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, title: { color: colors.text, fontWeight: '900' }, description: { color: colors.textMuted }, actions: { flexDirection: 'row', gap: 8 }, grow: { flex: 1 } });
