import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { NavigationProp, useNavigation } from '@react-navigation/native';
import { Feather } from '@expo/vector-icons';

import { apiRequest } from '../api/api-client'; import { useAuth } from '../auth/AuthContext';
import { Screen } from '../components/ui/Screen'; import { SectionHeader } from '../components/ui/SectionHeader'; import { StateView } from '../components/ui/StateView';
import { RootStackParamList } from '../navigation/types'; import { colors } from '../theme/colors'; import { Professional, ProfessionalsResponse, Service } from '../types/api';

export function HomeScreen() {
  const navigation = useNavigation<NavigationProp<RootStackParamList>>(); const { user } = useAuth();
  const [services, setServices] = useState<Service[]>([]); const [professionals, setProfessionals] = useState<Professional[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { Promise.all([apiRequest<Service[]>('/services'), apiRequest<ProfessionalsResponse>('/professionals?limit=8')]).then(([serviceList, response]) => { setServices(serviceList); setProfessionals(response.professionals.filter(professional => professional.id !== user?.id)); }).finally(() => setLoading(false)); }, [user?.id]);
  return <Screen header={<View style={styles.header}><View><Text style={styles.greeting}>Olá, {user?.name.split(' ')[0]}!</Text><Text style={styles.question}>Onde você precisa de ajuda hoje?</Text></View><Pressable onPress={() => navigation.navigate('Notifications')} style={styles.iconButton}><Feather name="bell" size={20} color={colors.text} /></Pressable></View>}>
    <View style={styles.location}><Feather name="map-pin" size={16} color={colors.accent} /><Text style={styles.muted}>Serviços perto de você</Text></View>
    <Pressable style={styles.search} onPress={() => navigation.navigate('Services')}><Feather name="search" size={20} color={colors.textMuted} /><Text style={styles.muted}>Buscar serviço</Text></Pressable>
    <SectionHeader eyebrow="Categorias" title="Resolva sua casa" description="Encontre especialistas verificados para cada necessidade." />
    {loading ? <StateView loading message="Carregando serviços..." /> : <View style={styles.grid}>{services.slice(0, 6).map(service => <Pressable key={service.id} style={styles.category} onPress={() => navigation.navigate('Services')}><Text style={styles.categoryMark}>{service.name.slice(0, 2).toUpperCase()}</Text><Text style={styles.categoryName}>{service.name}</Text></Pressable>)}</View>}
    <View style={styles.rowTitle}><Text style={styles.sectionTitle}>Profissionais recomendados</Text><Feather name="chevron-right" size={18} color={colors.primary} /></View>
    {professionals.slice(0, 4).map(professional => <Pressable key={professional.id} style={styles.professional} onPress={() => navigation.navigate('Professional', { professionalId: professional.id })}><View style={styles.avatar}><Text style={styles.avatarText}>{professional.name.charAt(0)}</Text></View><View style={styles.grow}><Text style={styles.professionalName}>{professional.name}</Text><Text style={styles.muted}>{professional.city}, {professional.state}</Text></View><Text style={styles.rating}>★ {professional.metrics?.averageRating || 'Novo'}</Text></Pressable>)}
  </Screen>;
}
const styles = StyleSheet.create({ header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, greeting: { color: colors.textMuted, fontSize: 14 }, question: { color: colors.text, fontSize: 20, fontWeight: '800', maxWidth: 260 }, iconButton: { width: 44, height: 44, borderRadius: 22, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.border }, location: { flexDirection: 'row', gap: 6, alignItems: 'center' }, search: { minHeight: 54, borderRadius: 16, backgroundColor: colors.surface, flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 16, borderWidth: 1, borderColor: colors.border }, muted: { color: colors.textMuted }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, category: { width: '31%', minHeight: 105, borderRadius: 18, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center', gap: 8, borderWidth: 1, borderColor: colors.border, padding: 8 }, categoryMark: { color: colors.primary, fontSize: 18, fontWeight: '900' }, categoryName: { color: colors.text, fontSize: 12, fontWeight: '700', textAlign: 'center' }, rowTitle: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, sectionTitle: { color: colors.text, fontSize: 17, fontWeight: '800' }, professional: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: colors.surface, padding: 14, borderRadius: 18, borderWidth: 1, borderColor: colors.border }, avatar: { width: 48, height: 48, borderRadius: 24, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: colors.white, fontSize: 18, fontWeight: '800' }, grow: { flex: 1 }, professionalName: { color: colors.text, fontWeight: '800' }, rating: { color: colors.warning, fontWeight: '700' } });
