export const copy = {
  hook: ["Sua casa", "precisa de", "alguma coisa?"],
  problems: "Todo mundo precisa de uma ajuda em casa.",
  app: "Agora ficou fácil encontrar quem resolve.",
  search: "Encontre profissionais próximos de você.",
  trust: "Escolha com confiança.",
  request: "Conte o que você precisa.",
  proposal: ["Compare.", "Escolha.", "Contrate."],
  chat: "Tudo direto pelo aplicativo.",
  success: "Simples do começo ao fim.",
  ecosystem: "Tudo conectado. Tudo mais fácil.",
  brand: "HOME EASY",
  tagline: "Sua casa precisa. A gente resolve.",
  action: "Encontre. Contrate. Resolva.",
  searchPlaceholder: "Buscar serviço ou profissional",
  services: ["Elétrica", "Limpeza", "Pintura", "Encanamento", "Montagem"],
  requestSteps: ["Descrição", "Data", "Horário", "Anexos"],
  city: "Recife, PE",
  mapCity: "Recife",
  nearby: "Profissionais perto de você",
  greeting: "Olá, Álvaro!",
  homeQuestion: "Como podemos te ajudar hoje?",
  recommended: "Profissionais recomendados",
  compactServices: ["Elétrica", "Limpeza", "Babá", "Montagem"],
  searchQuery: "Eletricista",
  searchResults: [
    { name: "Yasmim Sales", detail: "Eletricista · 1,2 km" },
    { name: "Carlos Lima", detail: "Eletricista · 2,4 km" },
    { name: "Marina Costa", detail: "Eletricista · 3,1 km" },
  ],
  selectedProfessional: {
    name: "Yasmim Sales",
    location: "Eletricista · Recife, PE",
    mapDetail: "Verificada · 1,2 km · Disponível",
    completed: "127 serviços realizados",
    verified: "Identidade verificada",
    review: "“Excelente profissional. Pontual e cuidadosa.”",
  },
  requestButton: "Solicitar serviço",
  chooseButton: "Escolher",
  proposals: [
    { name: "Yasmim Sales", price: "R$ 180", time: "Amanhã, 14h" },
    { name: "Carlos Lima", price: "R$ 210", time: "Amanhã, 16h" },
    { name: "Marina Costa", price: "R$ 195", time: "Sexta, 9h" },
  ],
  conversation: {
    first: "Olá! Consigo realizar amanhã às 14h.",
    response: "Ótimo! Pode trazer o material?",
    confirmation: "Sim, levo tudo que for necessário.",
    attachment: "foto-do-serviço.jpg",
    read: "Lida • 14:36",
    placeholder: "Mensagem...",
    online: "● Online",
  },
  completedTitle: "Serviço concluído.",
  ecosystemTiles: ["Perto de você", "Profissionais", "Conversa", "Agenda", "Avaliações", "Notificações"],
  sceneLabels: ["HOME EASY / 01", "01 / O APP", "02 / ENCONTRE", "03 / CONFIANÇA", "04 / SOLICITE", "05 / PROPOSTAS", "06 / CONVERSE", "07 / CONCLUÍDO"],
  resolveWatermark: "RESOLVER",
  introSubline: "O jeito simples de resolver.",
} as const;
