import { Feather } from '@expo/vector-icons';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import { NavigationContainer } from '@react-navigation/native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';

import { useAuth } from '../auth/AuthContext';
import { AboutScreen } from '../screens/AboutScreen'; import { AdminScreen } from '../screens/AdminScreen'; import { BecomeProfessionalScreen } from '../screens/BecomeProfessionalScreen'; import { ChatScreen } from '../screens/ChatScreen'; import { ContactScreen } from '../screens/ContactScreen'; import { ConversationsScreen } from '../screens/ConversationsScreen'; import { DisputeScreen } from '../screens/DisputeScreen'; import { EditProfileScreen } from '../screens/EditProfileScreen'; import { FavoritesScreen } from '../screens/FavoritesScreen'; import { ForgotPasswordScreen } from '../screens/ForgotPasswordScreen'; import { HomeScreen } from '../screens/HomeScreen'; import { HowItWorksScreen } from '../screens/HowItWorksScreen'; import { LoginScreen } from '../screens/LoginScreen'; import { NotificationsScreen } from '../screens/NotificationsScreen'; import { OpportunitiesScreen } from '../screens/OpportunitiesScreen'; import { OrderDetailScreen } from '../screens/OrderDetailScreen'; import { ProfessionalManagerScreen } from '../screens/ProfessionalManagerScreen'; import { ProfessionalReviewsScreen } from '../screens/ProfessionalReviewsScreen'; import { ProfessionalScreen } from '../screens/ProfessionalScreen'; import { ProfileScreen } from '../screens/ProfileScreen'; import { ProposalFormScreen } from '../screens/ProposalFormScreen'; import { PublicHomeScreen } from '../screens/PublicHomeScreen'; import { RegionalMapScreen } from '../screens/RegionalMapScreen'; import { ReportScreen } from '../screens/ReportScreen'; import { RequestDetailScreen } from '../screens/RequestDetailScreen'; import { RequestFormScreen } from '../screens/RequestFormScreen'; import { RequestsScreen } from '../screens/RequestsScreen'; import { ResetPasswordScreen } from '../screens/ResetPasswordScreen'; import { ScheduleScreen } from '../screens/ScheduleScreen'; import { ServiceProfessionalsScreen } from '../screens/ServiceProfessionalsScreen'; import { ServicesScreen } from '../screens/ServicesScreen'; import { SplashScreen } from '../screens/SplashScreen'; import { VerificationScreen } from '../screens/VerificationScreen';
import { colors } from '../theme/colors';
import { AppTabParamList, RootStackParamList } from './types';

const Stack = createNativeStackNavigator<RootStackParamList>(); const Tabs = createBottomTabNavigator<AppTabParamList>();
const tabIcons: Record<keyof AppTabParamList, keyof typeof Feather.glyphMap> = { Home: 'home', Requests: 'clipboard', Conversations: 'message-circle', Profile: 'user' };

function AppTabs() { return <Tabs.Navigator screenOptions={({ route }) => ({ headerShown: false, tabBarActiveTintColor: colors.accent, tabBarInactiveTintColor: colors.textMuted, tabBarStyle: { height: 68, paddingTop: 8, paddingBottom: 8, borderTopColor: colors.border, backgroundColor: colors.surface }, tabBarIcon: ({ color, size }) => <Feather name={tabIcons[route.name]} color={color} size={size} /> })}><Tabs.Screen name="Home" component={HomeScreen} options={{ title: 'Início' }} /><Tabs.Screen name="Requests" component={RequestsScreen} options={{ title: 'Pedidos' }} /><Tabs.Screen name="Conversations" component={ConversationsScreen} options={{ title: 'Mensagens' }} /><Tabs.Screen name="Profile" component={ProfileScreen} options={{ title: 'Perfil' }} /></Tabs.Navigator>; }

export function AppNavigator() { const { user, loading } = useAuth(); if (loading) return <SplashScreen />; return <NavigationContainer><Stack.Navigator screenOptions={{ headerTintColor: colors.primary, headerShadowVisible: false, headerStyle: { backgroundColor: colors.background }, contentStyle: { backgroundColor: colors.background } }}>
  {user ? <Stack.Screen name="App" component={AppTabs} options={{ headerShown: false }} /> : <Stack.Screen name="PublicHome" component={PublicHomeScreen} options={{ headerShown: false }} />}
  {!user && <><Stack.Screen name="Login" component={LoginScreen} options={{ headerShown: false }} /><Stack.Screen name="ForgotPassword" component={ForgotPasswordScreen} options={{ headerShown: false }} /><Stack.Screen name="ResetPassword" component={ResetPasswordScreen} options={{ headerShown: false }} /></>}
  <Stack.Screen name="HowItWorks" component={HowItWorksScreen} options={{ title: 'Como funciona' }} /><Stack.Screen name="BecomeProfessional" component={BecomeProfessionalScreen} options={{ title: 'Para profissionais' }} /><Stack.Screen name="About" component={AboutScreen} options={{ title: 'Sobre' }} /><Stack.Screen name="Contact" component={ContactScreen} options={{ title: 'Contato' }} /><Stack.Screen name="Services" component={ServicesScreen} options={{ title: 'Serviços' }} /><Stack.Screen name="ServiceProfessionals" component={ServiceProfessionalsScreen} options={{ title: 'Profissionais' }} /><Stack.Screen name="Professional" component={ProfessionalScreen} options={{ title: 'Profissional' }} /><Stack.Screen name="ProfessionalReviews" component={ProfessionalReviewsScreen} options={{ title: 'Avaliações' }} /><Stack.Screen name="RegionalMap" component={RegionalMapScreen} options={{ title: 'Mapa regional' }} />
  {user && <><Stack.Screen name="RequestForm" component={RequestFormScreen} options={{ title: 'Nova solicitação' }} /><Stack.Screen name="RequestDetail" component={RequestDetailScreen} options={{ title: 'Solicitação' }} /><Stack.Screen name="ProposalForm" component={ProposalFormScreen} options={{ title: 'Enviar proposta' }} /><Stack.Screen name="OrderDetail" component={OrderDetailScreen} options={{ title: 'Pedido' }} /><Stack.Screen name="Chat" component={ChatScreen} options={{ title: 'Conversa' }} /><Stack.Screen name="EditProfile" component={EditProfileScreen} options={{ title: 'Editar perfil' }} /><Stack.Screen name="Favorites" component={FavoritesScreen} options={{ title: 'Favoritos' }} /><Stack.Screen name="ProfessionalManager" component={ProfessionalManagerScreen} options={{ title: 'Área profissional' }} /><Stack.Screen name="Schedule" component={ScheduleScreen} options={{ title: 'Agenda' }} /><Stack.Screen name="Verification" component={VerificationScreen} options={{ title: 'Verificação' }} /><Stack.Screen name="Admin" component={AdminScreen} options={{ title: 'Administração' }} /><Stack.Screen name="Opportunities" component={OpportunitiesScreen} options={{ title: 'Oportunidades' }} /><Stack.Screen name="Report" component={ReportScreen} options={{ title: 'Denúncia' }} /><Stack.Screen name="Dispute" component={DisputeScreen} options={{ title: 'Disputa' }} /><Stack.Screen name="Notifications" component={NotificationsScreen} options={{ title: 'Notificações' }} /></>}
</Stack.Navigator></NavigationContainer>; }
